version: '3.8'

services:
  vaultwarden:
    image: vaultwarden/server:latest
    volumes:
      - vaultwarden-data:/data
    environment:
      - DOMAIN=http://vault.local
      - SIGNUPS_ALLOWED=true
      - WEBSOCKET_ENABLED=true
    networks:
      - traefik-public
    deploy:
      placement:
        constraints: [node.role == manager]
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.vaultwarden.rule=Host(`vault.local`)"
        - "traefik.http.routers.vaultwarden.tls=true"
        - "traefik.http.services.vaultwarden.loadbalancer.server.port=80"

volumes:
  vaultwarden-data:

networks:
  traefik-public:
    external: true
