version: '3.8'

services:
  router:
    image: tailscale/tailscale:latest
    hostname: swarm-manager-1
    environment:
      - TS_AUTHKEY_FILE=/run/secrets/tailscale_auth_key
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
      - TS_ROUTES=192.168.99.0/24
      - TS_EXTRA_ARGS=--advertise-exit-node --advertise-tags=tag:homelab
      - TS_ACCEPT_DNS=true
    volumes:
      - tailscale-state:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    secrets:
      - tailscale_auth_key
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    networks:
      - tailscale
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
          - node.hostname == swarm-manager-1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
      labels:
        - "com.tailscale.role=subnet-router"
        - "com.tailscale.role=exit-node"

secrets:
  tailscale_auth_key:
    external: true

volumes:
  tailscale-state:
    driver: local

networks:
  tailscale:
    driver: overlay
    name: tailscale
    attachable: true
