version: '3.8'

services:
  forgejo:
    image: codeberg.org/forgejo/forgejo:1.21
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - FORGEJO__database__DB_TYPE=sqlite3
      - FORGEJO__server__DOMAIN=git.local
      - FORGEJO__server__ROOT_URL=http://git.local
      - FORGEJO__server__HTTP_PORT=3000
      - FORGEJO__webhook__ALLOWED_HOST_LIST=private
      - FORGEJO__actions__ENABLED=true
      - FORGEJO__actions__DEFAULT_ACTIONS_URL=https://code.forgejo.org
    volumes:
      - forgejo-data:/data
    networks:
      - traefik-public
      - backend
    deploy:
      placement:
        constraints: [node.role == manager]
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.forgejo.rule=Host(`git.local`)"
        - "traefik.http.services.forgejo.loadbalancer.server.port=3000"

volumes:
  forgejo-data:

networks:
  traefik-public:
    external: true
  backend:
    external: true
    name: backend
