version: '3.8'

services:
  adguard:
    image: adguard/adguardhome:latest
    ports:
      - target: 53
        published: 53
        protocol: tcp
        mode: host
      - target: 53
        published: 53
        protocol: udp
        mode: host
      - target: 853
        published: 853
        protocol: tcp
        mode: host
    volumes:
      - adguard-work:/opt/adguardhome/work
      - adguard-conf:/opt/adguardhome/conf
    secrets:
      - adguard_username
      - adguard_password_hash
    configs:
      - source: adguard_config_template
        target: /tmp/AdGuardHome.yaml.template
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        # Read secrets
        USERNAME=$$(cat /run/secrets/adguard_username)
        PASSWORD_HASH=$$(cat /run/secrets/adguard_password_hash)
        
        # Generate config if it doesn't exist
        if [ ! -f /opt/adguardhome/conf/AdGuardHome.yaml ]; then
          # Replace placeholders in template
          sed -e "s|{{USERNAME}}|$$USERNAME|g" \
              -e "s|{{PASSWORD_HASH}}|$$PASSWORD_HASH|g" \
              /tmp/AdGuardHome.yaml.template > /opt/adguardhome/conf/AdGuardHome.yaml
          echo "Generated AdGuardHome.yaml from template"
        fi
        
        exec /opt/adguardhome/AdGuardHome --no-check-update -c /opt/adguardhome/conf/AdGuardHome.yaml -w /opt/adguardhome/work
    networks:
      - traefik-public
    deploy:
      placement:
        constraints: [node.role == manager]
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.adguard.rule=Host(`adguard.local`)"
        - "traefik.http.services.adguard.loadbalancer.server.port=80"

secrets:
  adguard_username:
    external: true
  adguard_password_hash:
    external: true

volumes:
  adguard-work:
  adguard-conf:

configs:
  adguard_config_template:
    file: ./config/AdGuardHome.yaml.template

networks:
  traefik-public:
    external: true
