version: '3.8'

services:
  adguard:
    image: adguard/adguardhome:latest
    environment:
      # Tell AdGuard it's behind a reverse proxy
      - AGH_REVERSE_PROXY=1
    ports:
      - target: 53
        published: 53
        protocol: tcp
        mode: host
      - target: 53
        published: 53
        protocol: udp
        mode: host
      - target: 853
        published: 853
        protocol: tcp
        mode: host
    volumes:
      - adguard-work:/opt/adguardhome/work
      - adguard-conf:/opt/adguardhome/conf
    secrets:
      - adguard_username
      - adguard_password_hash
    configs:
      - source: adguard_config_template
        target: /tmp/AdGuardHome.yaml.template
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        echo "=== AdGuard Configuration Setup ==="
        
        # Read secrets
        USERNAME=$$(cat /run/secrets/adguard_username)
        PASSWORD_HASH=$$(cat /run/secrets/adguard_password_hash)
        
        echo "Username: $$USERNAME"
        
        # Always regenerate config to ensure placeholders are replaced
        echo "Generating AdGuardHome.yaml from template..."
        sed -e "s|{{USERNAME}}|$$USERNAME|g" \
            -e "s|{{PASSWORD_HASH}}|$$PASSWORD_HASH|g" \
            /tmp/AdGuardHome.yaml.template > /opt/adguardhome/conf/AdGuardHome.yaml
        
        echo "Configuration generated successfully"
        
        echo "=== Starting AdGuard Home ==="
        exec /opt/adguardhome/AdGuardHome --no-check-update -c /opt/adguardhome/conf/AdGuardHome.yaml -w /opt/adguardhome/work
    networks:
      - traefik-public
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik-public"
        - "traefik.http.routers.adguard.rule=Host(`adguard.local`)"
        - "traefik.http.routers.adguard.entrypoints=web"
        - "traefik.http.services.adguard.loadbalancer.server.port=80"
        # Ensure host header is preserved
        - "traefik.http.services.adguard.loadbalancer.passhostheader=true"
        # Custom middleware to set proper headers
        - "traefik.http.middlewares.adguard-headers.headers.customrequestheaders.X-Forwarded-Host=adguard.local"
        - "traefik.http.middlewares.adguard-headers.headers.customrequestheaders.X-Forwarded-Proto=http"
        - "traefik.http.middlewares.adguard-headers.headers.customrequestheaders.X-Forwarded-Port=80"
        - "traefik.http.routers.adguard.middlewares=adguard-headers"

secrets:
  adguard_username:
    external: true
  adguard_password_hash:
    external: true

volumes:
  adguard-work:
  adguard-conf:

configs:
  adguard_config_template:
    file: ./config/AdGuardHome.yaml.template

networks:
  traefik-public:
    external: true
