version: '3.8'

services:
  adguard:
    image: adguard/adguardhome:latest
    ports:
      - target: 53
        published: 53
        protocol: tcp
        mode: host
      - target: 53
        published: 53
        protocol: udp
        mode: host
      - target: 853
        published: 853
        protocol: tcp
        mode: host
    volumes:
      - adguard-work:/opt/adguardhome/work
      - adguard-conf:/opt/adguardhome/conf
    configs:
      - source: adguard_config_template
        target: /tmp/AdGuardHome.yaml.example
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        if [ ! -f /opt/adguardhome/conf/AdGuardHome.yaml ]; then
          cp /tmp/AdGuardHome.yaml.example /opt/adguardhome/conf/AdGuardHome.yaml
        fi
        exec /opt/adguardhome/AdGuardHome --no-check-update -c /opt/adguardhome/conf/AdGuardHome.yaml -w /opt/adguardhome/work
    networks:
      - traefik-public
    deploy:
      placement:
        constraints: [node.role == manager]
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.adguard.rule=Host(`adguard.local`)"
        - "traefik.http.services.adguard.loadbalancer.server.port=80"

volumes:
  adguard-work:
  adguard-conf:

configs:
  adguard_config_template:
    file: ./AdGuardHome.yaml.example

networks:
  traefik-public:
    external: true
