version: '3.8'

services:
  adguard:
    image: adguard/adguardhome:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "853:853/tcp"  # DNS-over-TLS
    volumes:
      - adguard-work:/opt/adguardhome/work
      - adguard-conf:/opt/adguardhome/conf
    networks:
      - traefik-public
    deploy:
      placement:
        constraints: [node.role == manager]
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.adguard.rule=Host(`adguard.local`)"
        - "traefik.http.services.adguard.loadbalancer.server.port=3000"

volumes:
  adguard-work:
  adguard-conf:

networks:
  traefik-public:
    external: true
