version: '3.8'

# Single-node MinIO for object storage
# Simple, reliable, ~200MB RAM

services:
  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=${MINIO_PASSWORD}
    volumes:
      - minio-data:/data
    networks:
      - traefik-public
    ports:
      - target: 9000
        published: 9000
        mode: host
      - target: 9001
        published: 9001
        mode: host
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == swarm-manager-1
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.minio.rule=Host(`minio.local`)"
        - "traefik.http.services.minio.loadbalancer.server.port=9001"

volumes:
  minio-data:

networks:
  traefik-public:
    external: true
