version: '3.8'

services:
  ntfy:
    image: binwiederhier/ntfy:latest
    command:
      - serve
    environment:
      - NTFY_BASE_URL=http://ntfy.local
      - NTFY_CACHE_FILE=/var/cache/ntfy/cache.db
      - NTFY_AUTH_FILE=/var/lib/ntfy/auth.db
      - NTFY_AUTH_DEFAULT_ACCESS=deny-all
      - NTFY_BEHIND_PROXY=true
      - NTFY_UPSTREAM_BASE_URL=https://ntfy.sh
    volumes:
      - ntfy-cache:/var/cache/ntfy
      - ntfy-data:/var/lib/ntfy
    networks:
      - traefik-public
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.ntfy.rule=Host(`ntfy.local`)"
        - "traefik.http.routers.ntfy.entrypoints=web"
        - "traefik.http.services.ntfy.loadbalancer.server.port=80"

volumes:
  ntfy-cache:
  ntfy-data:

networks:
  traefik-public:
    external: true
