version: '3.8'

services:
  jit-proxy:
    image: nginx:alpine
    configs:
      - source: nginx_config
        target: /etc/nginx/nginx.conf
      - source: splash_page
        target: /usr/share/nginx/html/index.html
    networks:
      - traefik-public
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      labels:
        # Catch requests for stopped services
        - "traefik.enable=true"
        - "traefik.http.routers.mealie-jit.rule=Host(`recipes.local`)"
        - "traefik.http.routers.mealie-jit.priority=1"
        - "traefik.http.services.mealie-jit.loadbalancer.server.port=80"

configs:
  nginx_config:
    file: ./jit-proxy-nginx.conf
  splash_page:
    file: ./jit-splash.html

networks:
  traefik-public:
    external: true
