version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.retention.time=7d'
      - '--web.enable-lifecycle'
    volumes:
      - prometheus-data:/prometheus
    configs:
      - source: prometheus_config
        target: /etc/prometheus/prometheus.yml
      - source: alert_rules
        target: /etc/prometheus/alert-rules.yml
    networks:
      - traefik-public
      - monitoring
    deploy:
      placement:
        constraints: [node.role == manager]
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.prometheus.rule=Host(`prometheus.local`)"
        - "traefik.http.services.prometheus.loadbalancer.server.port=9090"

  alertmanager:
    image: prom/alertmanager:latest
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--storage.path=/alertmanager'
    volumes:
      - alertmanager-data:/alertmanager
    configs:
      - source: alertmanager_config
        target: /etc/alertmanager/alertmanager.yml
    networks:
      - traefik-public
      - monitoring
    deploy:
      placement:
        constraints: [node.role == manager]
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.alertmanager.rule=Host(`alertmanager.local`)"
        - "traefik.http.services.alertmanager.loadbalancer.server.port=9093"

  grafana:
    image: grafana/grafana:latest
    volumes:
      - grafana-data:/var/lib/grafana
    configs:
      - source: grafana_datasource
        target: /etc/grafana/provisioning/datasources/prometheus.yml
      - source: grafana_dashboard_config
        target: /etc/grafana/provisioning/dashboards/default.yml
      - source: flatcar_dashboard
        target: /etc/grafana/provisioning/dashboards/flatcar-swarm-overview.json
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
    networks:
      - traefik-public
      - monitoring
    deploy:
      placement:
        constraints: [node.role == manager]
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.grafana.rule=Host(`grafana.local`)"
        - "traefik.http.services.grafana.loadbalancer.server.port=3000"

  node-exporter:
    image: prom/node-exporter:latest
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    networks:
      - monitoring
    deploy:
      mode: global

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - monitoring
    deploy:
      mode: global

  swarm-exporter:
    image: alpine:latest
    command:
      - sh
      - -c
      - |
        apk add --no-cache docker-cli socat
        while true; do
          echo "HTTP/1.1 200 OK\r\nContent-Type: text/plain\r\n" > /tmp/header
          echo "# HELP swarm_node_info Node information" > /tmp/metrics
          echo "# TYPE swarm_node_info gauge" >> /tmp/metrics
          docker node ls --format '{{.Hostname}} {{.ManagerStatus}}' 2>/dev/null | while read hostname manager; do
            role="worker"
            [ -n "$$manager" ] && role="manager"
            echo "swarm_node_info{hostname=\"$$hostname\",role=\"$$role\"} 1" >> /tmp/metrics
          done
          echo "" >> /tmp/metrics
          echo "# HELP swarm_service_replicas_running Running replicas" >> /tmp/metrics
          echo "# TYPE swarm_service_replicas_running gauge" >> /tmp/metrics
          echo "# HELP swarm_service_replicas_desired Desired replicas" >> /tmp/metrics
          echo "# TYPE swarm_service_replicas_desired gauge" >> /tmp/metrics
          docker service ls --format '{{.Name}} {{.Replicas}}' 2>/dev/null | while read name replicas; do
            running=$${replicas%/*}
            desired=$${replicas#*/}
            echo "swarm_service_replicas_running{service_name=\"$$name\"} $$running" >> /tmp/metrics
            echo "swarm_service_replicas_desired{service_name=\"$$name\"} $$desired" >> /tmp/metrics
          done
          cat /tmp/header /tmp/metrics | socat -T1 TCP-LISTEN:9099,fork,reuseaddr -
        done
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - monitoring
    deploy:
      placement:
        constraints: [node.role == manager]
      replicas: 1

volumes:
  prometheus-data:
  alertmanager-data:
  grafana-data:

configs:
  prometheus_config:
    file: ./prometheus.yml
  alert_rules:
    file: ./alert-rules.yml
  alertmanager_config:
    file: ./alertmanager.yml
  grafana_datasource:
    file: ./provisioning/datasources/prometheus.yml
  grafana_dashboard_config:
    file: ./provisioning/dashboards/default.yml
  flatcar_dashboard:
    file: ./dashboards/flatcar-swarm-overview.json

networks:
  traefik-public:
    external: true
  monitoring:
    driver: overlay
